'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronRight,Home,Leaf,LogOut,MapPin,Plus,Settings2,Shirt,ShoppingBag,Sparkles,Wallet,X,Send,UserRound,Bookmark} from 'lucide-react';
import {Account,Profile,accountRequest} from '../../lib/account';
import s from '../account.module.css';
const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
export default function AccountPage(){
 const [account,setAccount]=useState<Account|null>(null),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{accountRequest('/api/account').then(d=>setAccount(d.user)).catch(()=>window.location.replace('/login/'));},[]);
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const f=new FormData(event.currentTarget);const profile:Profile={location:String(f.get('location')||''),home:split(String(f.get('home')||'')),pantry:split(String(f.get('pantry')||'')),likes:split(String(f.get('likes')||'')),dislikes:split(String(f.get('dislikes')||'')),sizes:{shirt:String(f.get('shirt')||''),shoes:String(f.get('shoes')||'')},budget:String(f.get('budget')||'')};try{const d=await accountRequest('/api/account',{method:'PUT',body:JSON.stringify({name:f.get('name'),profile})});setAccount(d.user);setEditing(false);setSaved(true);setTimeout(()=>setSaved(false),3500);}catch(e){setError(e instanceof Error?e.message:'Could not save your preferences.');}finally{setBusy(false);}}
 async function logout(){try{await accountRequest('/api/logout',{method:'POST'});window.location.assign('/login/');}catch{setError('Could not sign out. Please try again.');}}
 if(!account)return <main className={s.loading}><span className={s.logo}>reel<span>✳</span></span><p>Opening your space…</p></main>;
 const p=account.profile, first=account.name.split(' ')[0], initials=account.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();
 const completed=[p.home.length,p.pantry.length,p.likes.length,p.sizes.shirt||p.sizes.shoes,p.budget].filter(Boolean).length;
 return <main className={s.accountPage}>
  <header className={s.accountHeader}><a href="/" className={s.logo}>reel<span>✳</span></a><div className={s.headerLinks}><span className={s.currentNav}>Your space</span><a href="/">Explore the experience <ArrowUpRight size={13}/></a></div><button className={s.avatarButton} onClick={()=>setEditing(true)} aria-label="Edit your profile"><span>{initials}</span>{first}<ChevronRight size={14}/></button></header>
  <div className={s.dashboard}>
   <div className={s.welcome}><div><span className={s.eyebrow}>YOUR PERSONAL SHOPPING SPACE</span><h1>Good to see you, {first}<span>✳</span></h1><p>A few things about you. A world of better finds.</p></div><button className={s.secondary} onClick={()=>setEditing(true)}><Settings2 size={15}/> Edit preferences</button></div>
   {saved&&<div role="status" className={s.success}><Check size={16}/> Your preferences are saved.</div>}
   {error&&!editing&&<div role="alert" className={s.error}>{error}</div>}
   <div className={s.mainGrid}>
    <section className={s.profileCard}><div className={s.cardEyebrow}>THE PERSON BEHIND THE FINDS<span>01</span></div><div className={s.identity}><div className={s.bigAvatar}>{initials}<span>✳</span></div><h2>{account.name}</h2><p>{account.email}</p>{p.location&&<span className={s.location}><MapPin size={12}/>{p.location}</span>}</div><div className={s.preferenceProgress}><div><span>Your preferences</span><b>{completed} / 5</b></div><div className={s.progressTrack}><i style={{width:`${completed*20}%`}}/></div><p>{completed===5?'Your personal space is looking good.':'Add a little about yourself. Make this space yours.'}</p></div><button className={s.profileEdit} onClick={()=>setEditing(true)}>Make it more personal <ArrowRight size={15}/></button></section>
    <section className={s.startCard}><div className={s.cardEyebrow}>YOUR NEXT FAVOURITE STARTS HERE<ArrowUpRight size={15}/></div><div className={s.startCopy}><span className={s.eyebrow}>FROM FEED TO FIND</span><h2>See it.<br/>Send it.<br/><span>Make it yours.</span></h2><p>Send a Reel to your shopping assistant.<br/>Find a close match, then explore your options.</p><a href="https://t.me/sendtobrain_demo_bot" target="_blank" rel="noreferrer" className={s.primary}>Open Telegram <Send size={16}/></a></div><img src="/assets/sneaker.png" alt="Coral running sneaker" className={s.heroShoe}/><span className={s.heroProductCaption}>A LITTLE INSPIRATION GOES A LONG WAY.</span></section>
   </div>
   <div className={s.sectionHeading}><div><span className={s.eyebrow}>THE LITTLE DETAILS</span><h2>Your everyday, understood.</h2></div><span>Only the details you choose to share.</span></div>
   <div className={s.detailGrid}>
    <Detail icon={<Home size={20}/>} title="At home" eyebrow="WHAT YOU ALREADY OWN" items={p.home} empty="An oven? An air fryer? Tell us what’s in your kitchen." onEdit={()=>setEditing(true)}/>
    <Detail icon={<Leaf size={20}/>} title="In your pantry" eyebrow="THE INGREDIENTS ON HAND" items={p.pantry} empty="Keep a list of ingredients you already have." onEdit={()=>setEditing(true)}/>
    <Detail icon={<Shirt size={20}/>} title="Your fit" eyebrow="THE DETAILS THAT MATTER" items={[p.sizes.shirt&&`Clothing · ${p.sizes.shirt}`,p.sizes.shoes&&`Shoes · ${p.sizes.shoes}`].filter(Boolean)} empty="Save your usual sizes, ready for your next find." onEdit={()=>setEditing(true)}/>
   </div>
   <div className={s.bottomGrid}><section className={s.tasteCard}><div className={s.iconTile}><Sparkles size={19}/></div><div><span className={s.eyebrow}>YOUR KIND OF GOOD</span><h3>A little taste goes a long way.</h3><div className={s.chips}>{p.likes.length?p.likes.map(x=><span key={x}>{x}</span>):<p>Add the styles, products or foods you love.</p>}</div>{p.dislikes.length>0&&<p className={s.avoidText}>Prefer to skip: {p.dislikes.join(', ')}</p>}</div><button onClick={()=>setEditing(true)} aria-label="Edit your tastes"><Plus size={18}/></button></section><section className={s.budgetCard}><Wallet size={22}/><div><span className={s.eyebrow}>YOUR COMFORT ZONE</span><h3>{p.budget?`S$ ${Number(p.budget).toLocaleString()} per find`:'Set your shopping budget'}</h3><p>{p.budget?'Your saved preference for this account.':'Good finds should feel good, too.'}</p></div><button onClick={()=>setEditing(true)} aria-label="Edit your budget"><ChevronRight size={18}/></button></section></div>
   <footer className={s.dashboardFooter}><span>✳ A LITTLE MORE YOU. A LOT LESS SEARCHING.</span><button onClick={logout}><LogOut size={13}/> Sign out</button></footer>
  </div>
  {editing&&<div className={s.modalBackdrop} onClick={()=>{if(!busy)setEditing(false);}}><section className={s.modal} role="dialog" aria-modal="true" aria-labelledby="preferences-heading" onClick={e=>e.stopPropagation()}><div className={s.modalHeading}><div><span className={s.eyebrow}>MAKE YOURSELF AT HOME</span><h2 id="preferences-heading">The details that make you, you.</h2></div><button disabled={busy} onClick={()=>setEditing(false)} aria-label="Close preferences"><X size={20}/></button></div><p className={s.modalIntro}>Saved to your account. Your Telegram shopping flow stays as it is.</p><form method="post" onSubmit={save}><div className={s.formGrid}><label className={s.field}>Your name<input name="name" defaultValue={account.name} required maxLength={80}/></label><label className={s.field}>Where you shop<input name="location" defaultValue={p.location} placeholder="City or country"/></label></div><label className={s.field}>What you have at home<input name="home" defaultValue={p.home.join(', ')} placeholder="Oven, blender, coffee machine"/><small>Separate items with commas.</small></label><label className={s.field}>What’s in your pantry<input name="pantry" defaultValue={p.pantry.join(', ')} placeholder="Salt, olive oil, basil"/></label><div className={s.formGrid}><label className={s.field}>Things you love<input name="likes" defaultValue={p.likes.join(', ')} placeholder="Home cooking, running, timeless basics"/></label><label className={s.field}>Things you prefer to skip<input name="dislikes" defaultValue={p.dislikes.join(', ')} placeholder="Duplicate appliances, fast fashion"/></label></div><div className={s.formGridThree}><label className={s.field}>Clothing size<input name="shirt" defaultValue={p.sizes.shirt} placeholder="e.g. M"/></label><label className={s.field}>Shoe size<input name="shoes" defaultValue={p.sizes.shoes} placeholder="e.g. EU 42"/></label><label className={s.field}>Budget per find (S$)<input name="budget" type="number" min="0" max="100000" step="0.01" defaultValue={p.budget} placeholder="e.g. 100"/></label></div>{error&&<div className={s.error} role="alert">{error}</div>}<button className={s.primary} type="submit" disabled={busy}>{busy?'Saving…':'Save my preferences'}<Check size={16}/></button></form></section></div>}
 </main>
}
function Detail({icon,title,eyebrow,items,empty,onEdit}:{icon:React.ReactNode;title:string;eyebrow:string;items:string[];empty:string;onEdit:()=>void}){return <section className={s.detailCard}><div className={s.detailTop}><div className={s.iconTile}>{icon}</div><button onClick={onEdit} aria-label={'Edit '+title}><Plus size={17}/></button></div><span className={s.eyebrow}>{eyebrow}</span><h3>{title}</h3><div className={s.chips}>{items.length?items.map(x=><span key={x}>{x}</span>):<p>{empty}</p>}</div></section>}
